apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: foos.samplecontroller.k8s.io
spec:
  group: samplecontroller.k8s.io
  version: v1alpha1
  names:
    kind: Foo
    plural: foos
  scope: Namespaced
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: vms.samplecontroller.k8s.io
spec:
  group: samplecontroller.k8s.io
  version: v1alpha1
  names:
    kind: VM
    plural: vms
  scope: Namespaced
  additionalPrinterColumns:
  - name: Status
    type: string
    description: The VM Phase
    JSONPath: .status.phase
  - name: CPU
    type: integer
    description: The VM Phase
    JSONPath: .status.cpuUtilization
  - name: Age
    type: date
    JSONPath: .metadata.creationTimestamp
  validation:
    openAPIV3Schema:
      properties:
        spec:
          properties:
            vmName:
              type: string
              pattern: '^[-_a-zA-Z0-9]+$'
            cpu:
              type: integer
              minimum: 1
            memory:
              type: integer
              minimum: 128
            diskSize:
              type: integer
              minimum: 1